---
title: "sibei try2"
author: "Sibei Liu sl4660"
date: "2020/5/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(invgamma)
library(tidyverse)
library(MASS)
library(dplyr)
library(data.table)
library(caret)
library(emdbook)
library(truncnorm)
library(ModelMetrics)
library(patchwork)
```


```{r}
 data=read.csv("hurrican356.csv") %>% janitor::clean_names()
df=data %>% separate(time,into=c("sign","date","hour","sign2"),sep = c(1,9,18)) %>% select(-sign,-sign2) %>% group_by(id) %>%  
  mutate(
    date=as.Date(date, '%y-%m-%d'),
    begin=str_c(as.character(season),'0101'),
    initial=as.Date(begin, "%Y%m%d"),
    days=as.numeric(date-initial),
    final=str_c(date,hour),
    time=as.numeric(difftime(final,final[1],units = "hour")),
  ) %>% select(-begin,-initial) %>% filter(time%%6==0)
```

```{r}
df_all=split(df,df$id)
set.seed(2)
m=createDataPartition(1:356,p = 0.8,list = FALSE) %>% as.vector()

train=NULL
for(i in 1:max(m)){
if(i %in% m){
  train=rbind(train,df_all[[i]])
}}

train_df=split(train,train$id)
# train_df created

test_df=rbind(df_all[-m])
```

## from Xinru
```{r}
data=read.csv("hurrican356.csv") %>% janitor::clean_names()

## select 80% hurricanes as train data set
hurricanes = unique(as.character(data$id))
set.seed(2)
trRows <- createDataPartition(1:356,
                              p = 0.8,
                              list = FALSE)
train_hurricanes = hurricanes[trRows]
test_hurricanes = hurricanes[-trRows]

df=data %>% separate(time,into=c("sign","date","hour","sign2"),sep = c(1,9,18)) %>% dplyr::select(-sign,-sign2) %>%
  filter(hour == " 00:00:00" | hour == " 06:00:00" | hour == " 12:00:00" | hour == " 18:00:00") %>% 
  group_by(id)  %>%  
  mutate(
    date=as.Date(date, '%y-%m-%d'),
    begin=str_c(as.character(season),'0101'),
    initial=as.Date(begin, "%Y%m%d"),
    days=as.numeric(date-initial),
    final=str_c(date,hour),
    time=as.numeric(difftime(final,final[1],units = "hour")),
    nature = as.numeric(nature)-1
  ) %>% dplyr::select(-begin,-initial) 

## DS ET NR SS TS

df_train = df %>% 
  filter(id %in% train_hurricanes) %>% 
  mutate(
    shift_lat = shift(latitude, fill=NA,type="lag"),
    diff_lat = latitude - shift_lat,
    shift_long = shift(longitude, fill=NA,type="lag"),
    diff_long = longitude - shift_long,
    shift_wind = shift(wind_kt, fill=NA,type="lag"),
    diff_wind = wind_kt - shift_wind,
  ) %>% 
  drop_na()
  

df_test = df %>% 
  filter(id %in% test_hurricanes)  %>% 
  mutate(
    shift_lat = shift(latitude, fill=NA,type="lag"),
    diff_lat = latitude - shift_lat,
    shift_long = shift(longitude, fill=NA,type="lag"),
    diff_long = longitude - shift_long,
    shift_wind = shift(wind_kt, fill=NA,type="lag"),
    diff_wind = wind_kt - shift_wind,
  ) %>% 
  drop_na()

## time, days and id are created useful variables


```

```{r}
loglikelihood = NULL
loglikeli_func = function(dat,parameter){
  beta=parameter[1:7]
  sigma=parameter[8]
  rho=parameter[9]
  dat = dat %>% 
    mutate(
      shift_wind_2 = shift(wind_kt),
      mu = beta[1] + days*beta[2] + season*beta[3] + nature*beta[4] + diff_lat*beta[5] + diff_long*beta[6] + diff_wind*beta[7] + rho*shift_wind_2,
      loglikeli = -(wind_kt-mu)^2/(2*(sigma^2))-log(sqrt(2*pi)*sigma)
    ) %>% 
    drop_na()
  
  loglikelihood = sum(dat$loglikeli) + log(dmvnorm(beta, rep(0,7), diag(1,7))) + log(dtruncnorm(rho, a=0, b=1,mean=0.5,sd=1/5)) + log(dinvgamma(1/(sigma)^2, 0.001, 0.001))
  return(list(loglikelihood=loglikelihood,data=dat))
}

starting<- c(-28,0,0.01,0.001,0.01,0.01,0.5,1,1)
loglikeli_func(df_train,starting)$loglikelihood
```



```{r}
componentwiseMHstep <- function(dat,parameter,a) {
p <- length(parameter)
res <- parameter
for(i in 1:p) {
prop <- res
prop[i] <- parameter[i] + 2 * (runif(1) - 0.5) * a[i]
if(log(runif(1)) < loglikeli_func(dat,prop)$loglikelihood - loglikeli_func(dat,res)$loglikelihood)
res[i] <- prop[i]
}
names(res)=c(str_c("beta",0:6),"sigma","rho")
return(res)
}

componentwiseMHstep(df_train,c(0.1,-1,0.01,-0.5,0.1,0.1,0.1,3,1), a=c(0.05,0.001,0.01,0.05,0.05,0.1,0.01,0.1,0.01))
```


```{r}

df_train=df_train 

nrep <- 5000

starting<-   c(-26,0,0.012,0.009,0,0.01,1,0.1,1)
chain <- matrix(NA, nrep, length(starting))
parameter=starting
for(i in 1:nrep) {
newx <- componentwiseMHstep(df_train,parameter, a=c(0.1,0.0001,0.0001,0.01,0.001,0.01,0.001,0.02,0.0003))
chain[i,] <- newx
parameter <- newx}

colnames(chain)=c(str_c("beta",0:6),"sigma","rho")
 #chain[4980:5000,]
```

```{r}

length(unique(chain[,2]))
```

```{r}
chain=read_csv("chain") %>% dplyr::select(-X1)
df_chain=as.data.frame(chain)

colnames(df_chain)=c(str_c("beta",0:6),"sigma","rho","index")
var_name=c(str_c("beta",0:6),"sigma","rho","index")

p1 <- c(paste0('plot1_fluc',1:9))
  for(i in 1:9){
  assign(p1[i],ggplot(data = df_chain, aes_string(x = "index" , y = df_chain[,i]))  +
    geom_line() + 
    ggtitle(var_name[i]) + theme(plot.title = element_text(hjust = 0.5)))
    get(p1[i])
  }
plot1_fluc1
plot1_fluc2
plot1_fluc3
plot1_fluc4
plot1_fluc5
plot1_fluc6
plot1_fluc7
plot1_fluc8
plot1_fluc9

plot1_fluc1+plot1_fluc2+plot1_fluc3
plot1_fluc4+plot1_fluc5+plot1_fluc6
plot1_fluc7+plot1_fluc8+plot1_fluc9

## last several index to check if it enters the stationary 
p <- c(paste0('plot_fluc',1:9))
  for(i in 1:9){
  assign(p[i],ggplot(data = df_chain[3500:4000,], aes_string(x = index[3500:4000], y = df_chain[3500:4000,i]))  +
    geom_line() + 
    ggtitle(var_name[i]) + theme(plot.title = element_text(hjust = 0.5)))
    get(p[i])
  }
plot_fluc1
plot_fluc2
plot_fluc3
plot_fluc4
plot_fluc5
plot_fluc6
plot_fluc7
plot_fluc8
plot_fluc9
```

```{r}
mean_para=NULL
lower_par=NULL
upper_par=NULL
for (i in 1:9 ){
mean_para[i]=mean(df_chain[10000:20000,i])
lower_par[i]=quantile(df_chain[10000:20000,i],probs=0.025)
upper_par[i]=quantile(df_chain[10000:20000,i],probs=0.975)}

results=data.frame(mean=mean_para,lower=lower_par,upper=upper_par)
row.names(results)=c(str_c("beta",0:6),"sigma","rho")
results %>% knitr::kable()
```


```{r}
# to do prediction
pred_test=df_test %>% mutate(
  mu_pred = results[1,1] + days*results[2,1] + season*results[3,1] + nature*results[4,1] + diff_lat*results[5,1] + diff_long*results[6,1] + diff_wind*results[7,1] + results[8,1]*shift_wind,
  y_hat=mu_pred+shift_wind+rnorm(1,mean=0,sd=results[9,1])
)

MSE=mse(unlist(pred_test[,10]) %>% as.vector(),unlist(pred_test[,21]) %>% as.vector())

ggplot(data=pred_test)+geom_line(aes(x=x,y=wind_kt),color="black")+geom_line(aes(x=x,y=y_hat),color="blue")+labs(title="Fitted speed and observed speed",x="",y="Speed")

MSE
```



